config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update, :index]
  resources :groups, only:[:new, :create, :edit, :update, :index] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_messge_idよりも新しい(大きい)メッセージ達のみを取得
    @messages = group.messages.includes(:user).where("id > #{last_message_id}")
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
    @users = @group.users
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, {:user_ids => [] } )
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end
  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html {redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'}
        format.json
      end
    else
      respond_to do |format|
        format.html {flash.now[:alert] = 'メッセージを入力してください。'; render :index}
        format.json
      end
    end
  end
  private
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id, group_id: @group.id)
  end
  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :"チャットメンバーを追加",class:"chat-group-form__label"
    .chat-group-form__field--right
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      %input{type: "text", name: "keyword", id:"user-search-field",  placeholder:"追加したいユーザー名を入力してください", class: "chat-group-form__input"}
      .search_result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :"チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right
      .chat-group-form__field__member
        .chat-group-users.js-add-user
          .chat-group-user.clearfix.js-chat-member 
            -# =f.hidden_field  :"group[user_ids][]", value:"#{current_user.id}", id:"group_user_ids"
            %input{type:"hidden", name:"group[user_ids][]",value:"#{current_user.id}", id:"group_user_ids_#{current_user.id}"} 
            %p.chat-group-user__name
              = current_user.name
          -if group.id
            - @users.each do | user |
              - unless user.id == current_user.id 
                .chat-group-user.clearfix.js-chat-member 
                  %input{type:"hidden", name:"group[user_ids][]",value:"#{user.id}", id:"group_user_ids_#{user.id}"} 
                  %p.chat-group-user__name
                    = user.name
                  = link_to "削除","", class: "user-search-remove chat-group-user__btn chat-group-user__btn--remove js-remove-btn"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'devise/shared/side_bar'
  
  

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content:  "text/html; charset=UTF-8", "http-equiv": "Content-Type" }/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
%li.right-contents__messages__list__message{data: { "message-id": message.id} }
  .right-contents__messages__list__message__usertime
    %p.right-contents__messages__list__message__usertime_user<>
      = message.user.name
    %p.right-contents__messages__list__message__usertime_time<>
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  - if message.content.present?
    %p.right-contents__messages__list__message__text<>
      = message.content
  = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.wrapper
  = render 'devise/shared/side_bar'
  .right-contents
    .right-contents__header
      .right-contents__header__box
        .right-contents__header__box__group
          %p.right-contents__header__box__group__name
            = @group.name
          %ul.right-contents__header__box__group__members
            %li.right-contents__header__box__group__members__member<>
              %p.right-contents__header__box__group__members__member__name Member :
            - @group.users.each  do |user|
              %li.right-contents__header__box__group__members__member<>
                %p.right-contents__header__box__group__members__member__name
                  =user.name
        .right-contents__header__box__edit
          =link_to "Edit", edit_group_path(@group), class:"right-contents__header__box__edit__btn"
            

    .right-contents__messages
      %ul.right-contents__messages__list
        = render partial: 'message', collection: @messages

    .form
      = form_for [@group,@message] , html: {class: "new__message"} do |f|
        = f.text_field :content, class: "new__message__input__text", placeholder: "type a message"
        .form__mask
          = f.label :image, class: "new__message__input__image" do
            = fa_icon "image" , class: "new__message__input__image__icon"
            = f.file_field :image, class: "new__message__input__image__file"
        = f.submit "Send", class: "new__message__submit-btn"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップベージに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'